title: Devops Portfolio
description: "This is a website describing my portfolio"
theme: jekyll-theme-hacker

sass:
  style: compressed
  load_paths:
    - _sass

assets:
  styles:
    - assets/css/style.css
    - assets/css/custom.css
